// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductOperation;

#nullable disable

namespace ProductOperation.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220213043522_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProductOperation.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"), 1L, 1);

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Stock")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            Image = "images/nike.jpg",
                            Name = "Nike",
                            Price = 5000m,
                            Stock = 500m
                        },
                        new
                        {
                            ProductId = 2,
                            Image = "images/puma.jpg",
                            Name = "Puma",
                            Price = 2000m,
                            Stock = 400m
                        },
                        new
                        {
                            ProductId = 3,
                            Image = "images/Adidas.jpg",
                            Name = "Adidas",
                            Price = 3000m,
                            Stock = 500m
                        },
                        new
                        {
                            ProductId = 4,
                            Image = "images/Clarks.jpg",
                            Name = "Clarks",
                            Price = 5000m,
                            Stock = 600m
                        },
                        new
                        {
                            ProductId = 5,
                            Image = "images/Seeandwear.jpg",
                            Name = "Seeandwear",
                            Price = 2000m,
                            Stock = 400m
                        },
                        new
                        {
                            ProductId = 6,
                            Image = "images/Woodland.jpg",
                            Name = "Woodland",
                            Price = 2000m,
                            Stock = 500m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
